
-- Add more notification preference columns
ALTER TABLE public.notification_preferences
  ADD COLUMN IF NOT EXISTS email_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS push_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS meta_50 BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS meta_75 BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS meta_100 BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS meta_superada BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS alta_atividade BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS novos_clientes BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS relatorio_email BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS relatorio_frequencia TEXT NOT NULL DEFAULT 'semanal',
  ADD COLUMN IF NOT EXISTS meta_mensal NUMERIC NOT NULL DEFAULT 10000;
